SELECT * FROM UserReviews;
SELECT * FROM places;
SELECT * FROM cities;
SELECT * FROM cityplaces;
SELECT * FROM placereviews;
SELECT * FROM UserLog;
SELECT * FROM AdminLog;
SELECT * FROM UserDetails;
SELECT * FROM AdminDetails;